### ISSUE TITLE
Error: Cannot find module '../contracts/MoolaFix/zeroRateStrategies.js'

### ISSUE THREAD

**Issue by mookim-eth** [moolamarket/moola-fix#2]
running `npm run start -- --fork https://forno.celo.org --wallet.unlockedAccounts=0xd7f77169d5E6a32C5044052F9a49eb94697b25ED --miner.defaultGasPrice=0 --chain.hardfork=istanbul --chain.allowUnlimitedContractSize=true --miner.blockGasLimit=40000000` to bypass issue #1 

```
$ npm run test

> test@1.0.0 test
> truffle test

Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./contracts/adapters/AutoRepay.sol
> Compiling ./contracts/adapters/BaseUniswapAdapter.sol
> Compiling ./contracts/adapters/FlashLiquidationAdapter.sol
> Compiling ./contracts/adapters/LeverageBorrowAdapter.sol
> Compiling ./contracts/adapters/UniswapLiquiditySwapAdapter.sol
> Compiling ./contracts/adapters/UniswapRepayAdapter.sol
> Compiling ./contracts/adapters/interfaces/IBaseUniswapAdapter.sol
> Compiling ./contracts/interfaces/IUniswapV2Router02.sol
> Compiling ./contracts/mocks/swap/MockUniswapV2Router02.sol
> Artifacts written to /home/mookim/.tmp/test--64332-E8oaOb0ZpZao
> Compiled successfully using:
   - solc: 0.6.12+commit.27d51765.Emscripten.clang
  arguments:  0x0B1AbFE30018F24804a94a3a1C7b59c2B8Df1298 0x861DFe876A696eA926E389b3c69F37ACD49c3d9D 0xBBbe56b9f1F8047BaaCDCc022aF9585EAE14587a 0xc73E758F412A84dad13135229eB8d2192B63A476
Error: Cannot find module '../contracts/MoolaFix/zeroRateStrategies.js'
Require stack:
- /mnt/mpathu/mookim/moola-fix/test/test/moola-fix.js
- /mnt/mpathu/mookim/moola-fix/test/node_modules/mocha/lib/mocha.js
- /mnt/mpathu/mookim/moola-fix/test/node_modules/mocha/index.js
- /mnt/mpathu/mookim/moola-fix/test/node_modules/truffle/build/test.bundled.js
- /mnt/mpathu/mookim/moola-fix/test/node_modules/original-require/index.js
- /mnt/mpathu/mookim/moola-fix/test/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/mnt/mpathu/mookim/moola-fix/test/test/moola-fix.js:15:5)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /mnt/mpathu/mookim/moola-fix/test/node_modules/mocha/lib/mocha.js:417:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/mpathu/mookim/moola-fix/test/node_modules/mocha/lib/mocha.js:414:14)
    at Mocha.run (/mnt/mpathu/mookim/moola-fix/test/node_modules/mocha/lib/mocha.js:1015:10)
    at /mnt/mpathu/mookim/moola-fix/test/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:156:1
    at new Promise (<anonymous>)
    at Object.run (/mnt/mpathu/mookim/moola-fix/test/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:155:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.module.exports [as run] (/mnt/mpathu/mookim/moola-fix/test/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/run.js:115:1)
    at runCommand (/mnt/mpathu/mookim/moola-fix/test/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:201:1)
Truffle v5.6.2 (core: 5.6.2)
Node v16.18.0
```

**Comment by mookim-eth** [comment]
it seems this `zeroRateStrategyStableTwo` is not used, just remove should be fine

https://github.com/moolamarket/moola-fix/blob/23b84a613465ed49ce43c4ce18bc8d8039be07cd/test/test/moola-fix.js#L13-L15
